### ISSUE TITLE
can't reach the mAP

### ISSUE THREAD

**Issue by NickMinYang** [chengyangfu/caffe#16]
**It should reach 77.5* mAP at 80k iterations.**
Why I can't get this map?I just clone the code, and follow the readme.

**Comment by ghost** [comment]
yes, me too, i just got 60+, how about you?

**Comment by chengyangfu** [comment]
The problem comes from the synchronization issue between Wei(The first author of SSD) and mine. However, right now I have no intention to use Caffe anymore. That means I will not fix current Github version.  But I will release another version in PyTroch soon. and it will also fix some problems not mentioned in the paper.

**Comment by rabbitwayne** [comment]
@chengyangfu I have the same issue and mAP can only reach 0.68 during training. Can you say more about the synchronization issue? How to solve this problem in the current caffe release? When will you release the pytorch version of DSSD? Thanks!
